services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: simplex_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
         - es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 127.0.0.1:9200:9200
    mem_reservation: 4g

  ims:
    image: snomedinternational/identity-management-service:latest
    container_name: simplex_ims
    restart: always
    entrypoint: java -Xms100m -Xmx100m -cp @/app/jib-classpath-file org.snomed.ims.Application
    ports:
      - 8081:8080
    volumes:
      - ./ims/application.properties:/app/config/application.properties
      - ./ims/file_based_user_store:/app/file_based_user_store

  snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: simplex_snowstorm
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -cp @/app/jib-classpath-file org.snomed.snowstorm.SnowstormApplication
    networks:
      elastic:
        aliases:
         - snowstorm
    ports:
      - 8080:8080
    volumes:
      - ./snowstorm/application.properties:/app/config/application.properties

  browser:
    image: snomedinternational/snomedct-browser:latest
    container_name: simplex_browser
    depends_on:
      - snowstorm
    links:
      - snowstorm:snowstorm
    networks:
      - elastic
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 80:80
    restart: always


networks:
  elastic:

volumes:
  elastic:
